### ISSUE TITLE
idrac command processing failed 

### ISSUE THREAD

**Issue by kanapuliAthavan** [dell/Dell-EMC-Ansible-Modules-for-iDRAC#1] opened 2018-06-20 02:55 UTC
I am trying to change the SNMP community name using dellemc_configure_idrac_services module and my playbook is as follows 

```
**Play file**
---

- hosts: all
  gather_facts: False
  become: yes
  become_method: sudo
  user: root
  roles:
    - snmp-configure

**snmp-configure role main.yml**
---
- name: setup idrac community name
  dellemc_configure_idrac_services:
      idrac_ip: "xxx.xxx.xx.xx"
      idrac_user: "root"
      idrac_pwd: "xxxxx"
      share_name: "xxx.xxx.xx.xx/nfsfileshare"
      snmp_enable: "Enabled"
      community_name: "my_new-name"
  become: yes
```

When I try to run this play , I always get the following error as Command Processing Failed,

```
"module_stdout": "\rcmdstat\r\n\r\tstatus       : 2\r\n\r\tstatus_tag   : COMMAND PROCESSING FAILED\r\n\r\terror        : 252\r\n\r\terror_tag    : COMMAND SYNTAX ERROR\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 0

```

What could be the actual problem here?

**Comment by anupamaloke** [comment] 2018-06-21 10:50
I believe the issue is that you are using "become" and "become_sudo" with your playbook. The OpenManage Ansible Modules for iDRAC need to be executed on Ansible controller and they uses REST APIs to communicate with iDRAC. 
So you need to remove "become" and "become_sudo" from your playbook or use "delegate_to" in your tasks to run them locally. For e.g.

`
- name: setup idrac community name
  dellemc_configure_idrac_services:
      idrac_ip: "{{ idrac_ip}}"
      idrac_user: "{{ idrac_user}}"
      idrac_pwd: "{{ idrac_pwd}}"
      share_name: "{{ playbook_dir }}"
      snmp_enable: "Enabled"
      community_name: "my_new-name"
  delegate_to: localhost
`

**Comment by anupamaloke** [comment] 2018-07-19 07:55
Closing the issue as this is not a bug and can be fixed by making a playbook change to use local connection.

**Closed by anupamaloke** 2018-07-19 07:55 UTC
Labels: good first issue
